siteorigin/siteorigin-panels

inc/default-styles.php

Previously, the regex would only parse the css on the last line of the CSS Styles box.  Now, it parses every line.

Fix regex to match text in all rows

---

js/siteorigin-panels.js

Allow user to close widget adding window with [Esc] keyboard key. Also adding keyboard listener handler function. Actually the closing is not in the very elegant form but it is good start :)

Close widgets window with esc

---

inc/styles.php

I know there is no point of it at first glance but, actually in some cases alowing users to select in 'ex' or 'pt' will be overkill. Also with fn there is a way to uniform plugin enhancements.

Separate mesurement list

---

siteorigin-panels.php

I assume there's some reasoning the `panels_info` has explicitly been unset from the instance, but I have a seemingly basic use case that is difficult to achieve given the current behavior. Using `get_less_variables`, I'd like to be able to pass the configured `font_color` to the LESS styles so that I can lighten or darken colors in the stylesheet based on the configured font color. The proposed changes make this possible by allowing me to access `$instance['panels_info']['style']['font_color']`. Otherwise, without explicitly calling to and iterating over the `panels_data` post meta, I can't imagine any way to use these configuration options.
Any suggestions for another approach I could be taking here?

Allow panels_info to be passed to instance

---

inc/sidebars-emulator.php

The check for the home page was too simplified before, working only when WP was installed on the domain root. If it was installed inside path, ie. `http://domain.com/path/to/wp/` or when using WP network with paths for sites (my use case) the check failed.
Improved with more robust check, using `home_url()` and native PHP function `parse_url()`.
Tested on WP network and single site.
Q: is this plugin PHP unit tested?

Improved checking for home page in sidebars emulator

---

js/siteorigin-panels-styles.js
siteorigin-panels.php

Allow themes and plugins interact with wpColorPicker plugin settings. Useful in case of changing default color suggestions.

Allow themes and plugins interact with wpColorPicker Revamped PR #65

---

siteorigin-panels.php

Perhaps a bit of an edge case, but this checks to see whether the constant `SITEORIGIN_PANELS_JS_SUFFIX` is already defined, before defining it. 
This will allow developers to use non-minified scripts in local environments for debugging, without needing to run the `develop` branch of the plugin. Instead, they can define the constant as a blank string in their `wp-config.php` file. 
I looked and don't see any way this will interfere with the `gulpfile.js` release build script, but it may be a good idea to check.

Make JS_SUFFIX constant overrideable

---

siteorigin-panels.php

Related to #95.
It is fixing a bug when 2 same HTML classes were outputted for the native WP widgets. Now the `$classes` array goes through the [array_unique](http://php.net/manual/en/function.array-unique.php) (and though array_filter to remove all falsey values from array).

Only unique HTML classes in the widget output

---

widgets/basic.php

The query args 'additional' key was not being properly set to an empty array if no value was given. This caused a PHP warning when DEBUG is enabled. This modification ensures that $query_args['additional'] always gets set.

Set 'additional' key on query_args

---

js/siteorigin-panels-live-editor.js

Use `.so-panel` class to identify widget panels in live editor.

For GH-137: live editor not working when `.widget` class not used.

---

settings/settings.php
siteorigin-panels.php

Added tablet responsive setting, which defaults to 1024px and simply sets column widths to 50%.

Tablet responsive break point setting

---

js/siteorigin-panels.js
js/siteorigin-panels/view/builder.js

@gregpriday Please take a look. I'm not entirely sure why we were skipping setting PB content on the visual editor when it was empty, other than optimization. This was leaving behind PB content in the editor when the expectation seems to be that it should have been cleared.

Ensure PB content is cleared when switching back to visual editor.

---

tpl/admin-home-page.php

Vulnerable file **/siteorigin-panels/tpl/admin-home-page.php** do not properly escape **REQUEST_URI** that makes possible XSS attack.
Add ```esc_url()``` filtration to fix current vulnerability.

fix xss vulnerability

---

settings/settings.php

Same issue as siteorigin/so-widgets-bundle#325
"Google AppEngine does not auto-correct double slashes in a URL, [...] result[ing] in a 404 error"

Removed double slash

---

widgets/basic.php

If a user adds post__not_in to the additional field it'll cause a fatal error as [this line](https://github.com/siteorigin/siteorigin-panels/blob/develop/widgets/basic.php#L257) doesn't account for strings.
How to replicate this issue:
- Add the following into the additional field: post__not_in=372
This will cause the following error: PHP Fatal error:  [] operator not supported for strings in D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\widgets\basic.php on line 257
Stack Trace:
> [01-Nov-2016 07:35:18 UTC] PHP   1. {main}() D:\wamp\www\siteorigin\index.php:0
> [01-Nov-2016 07:35:18 UTC] PHP   2. require() D:\wamp\www\siteorigin\index.php:17
> [01-Nov-2016 07:35:18 UTC] PHP   3. require_once() D:\wamp\www\siteorigin\wp-blog-header.php:19
> [01-Nov-2016 07:35:18 UTC] PHP …

Corrected post__not_in issue for additional field

---

inc/default-styles.php

Resolves #257
This is a commonly sought after background image display setting. It's commonly misunderstood as a parallax, which is typically the reason people don't like the Parallax - it's just them misunderstanding what it is. [Here's a comparison between fixed and parallax](http://alex.siteorigin.net/parallax-vs-fixed/).
Adding fixed images is such an easy thing there's little reason for us not to include it. Please note that unlike the #257 suggestion, I opted not to include fixed (original) as, in hindsight, I don't feel like it needs one.
Should fixed be moved to a different location in the image display background drop down? It's currently after center but before Parallax.

PB 3.0: Add Fixed background support

---

inc/renderer.php

Resolves #250 
If you set a bottom margin of say, 0, it won't be applied to any of the widgets. This contradicts the global bottom setting as that setting _will_. This PR aims to correct this by applying the row defined bottom margin if set, and if not, defaulting to the global default.
This will not affect the last-child bottom margin.

PB 3.0: Apply row style bottom margin to widgets

---

js/siteorigin-panels/view/builder.js
js/siteorigin-panels/view/dialog.js

_.isUndefined() returns a reference error if TinyMCE isn't set ([reference](https://github.com/jashkenas/underscore/issues/250)). This means that if the visual editor is disabled (which can be done via the user profile) SiteOrigin Page Builder won't save any changes. Changing _.isUndefined() to a typeof check resolves this issue and allows the user to continue using SiteOrigin Page Builder.

Replace TinyMCE _.isUndefined()  check with a typeof

---

inc/admin.php

PB 3.0: Add WP Color Picker as a dependency for admin script

---

siteorigin-panels.php

On a fresh install with just SiteOrigin Page Builder installed, the color form fields will appear as just text fields due to the color picker not being enqueued.

Add WP Color Picker as a dependency for admin script

---

siteorigin-panels.php

As per #315 and [this Slack chat](https://siteorigin.slack.com/archives/plugins/p1475089831000049).
We should try using the higher than default priority for on the main content filter compatibility reasons.  Through my, admittedly limited, testing I wasn't able to run into any issues but as always it's possible issues may arise.

PB 3.0: Increase priority of main filter

---

css/admin.css
css/admin.less

On "Import/Export" section the "Insert" button has 3 options that are not visible because the z-index `.so-toolbar` is equal with `so-content`. See the screenshot, it says all.

The "Insert" options are not visible

---

siteorigin-panels.php

This PR adds is_live_editor() and a body_class.
body_class - Allow designers to hide certain elements that can cause issues when viewed via the live editor
conditional check: Allows for developers to easily output live editor specific JavaScript and styling

PB 3.0: is_live_editor()

---

siteorigin-panels.php

In certain situations, the SiteOrigin Page Builder (the_)content filter can be run outside of the loop. This can cause issues where certain plugins must be run only once. As a result, I've added a [in_the_loop()](https://codex.wordpress.org/Function_Reference/in_the_loop) check.
An example situation where this PR will help are the [Yoast Open Graph tags](https://github.com/siteorigin/so-widgets-bundle/issues/122). Yoast uses get_the_excerpt() to generate a description which in turn uses get_the_content(). This is done _way_ outside of the header which can cause issues with the aforementioned use case.

Add loop check to prevent SiteOrigin Page Builder from running too soon

---

inc/admin.php
inc/post-content-filters.php
inc/post-content.php
inc/renderer.php
inc/styles.php
js/siteorigin-panels/model/builder.js
js/siteorigin-panels/view/builder.js
siteorigin-panels.php
widgets/basic.php

This PR improves how Page Builder interacts with post_content. It's now possible to view a Page Builder page, even when the plugin is deactivated. This mainly works with Widgets Bundle widgets.
We can also parse post_content to extract the original Page Builder data.

Improved interaction with post_content

---

inc/renderer.php

$grid was not defined and therefor the cell class attribute was not working. This should fix that issue.

Define  as it wasn't defined

---

inc/admin-layouts.php
inc/admin.php
js/siteorigin-panels/dialog/prebuilt.js
tpl/js-templates.php

This change allows other themes and plugins to add their own layout directories. A server can be setup using the [Layout Viewer](https://github.com/siteorigin/layout-viewer) theme.

Custom Layout Directory

---

inc/styles.php

Mobile browsers disable fixed backgrounds. "Certain" browsers can do it in a really weird manner and result in the image being really zoomed in ([reference](https://stackoverflow.com/questions/22141681/css-background-images-resizing-incorrectly-on-ipad-and-iphone)). To resolve this issue, we need to set background-attachment: to scroll;.

Reset fixed background image display setting on mobile

---

inc/admin.php
siteorigin-panels.php

To fix #404. Ensure previews work without actually saving panels data to post meta.

Fix previews

---

inc/revisions.php

To fix #452. Prevent creating multiple new entries in post meta every time a post is previewed.

Prevent duplicate meta entries on preview

---

inc/admin.php
inc/functions.php
inc/live-editor.php
inc/renderer-legacy.php
inc/renderer.php
inc/settings.php
inc/styles.php
settings/tpl/settings.php
tpl/live-editor-preview.php

To fix #447. Avoid using relative asset URLs which may break caching plugins.

Avoid relative asset URLs

---

inc/styles.php

There's no reason to show this setting if it won't do anything due to Legacy Layout always being enabled.

Hide Cell Vertical Alignment options if Legacy Layout is set to always

---

siteorigin-panels.php

This will allow plugins and themes to easily enqueue cache friendly assets when they need to.

Content Cache: Add Enqueue hook

---

js/styling.js

on some themes(depending on jquery version) .load event causes a javascript error, here is the javascript error: 
`Uncaught TypeError: a.indexOf is not a function`
and this doesn't let the page builder to render the page.
.load event has been replaced by .on(...
additional info:
See bug [#11733](http://bugs.jquery.com/ticket/11733), which documents this deprecation:
> The .load() method is an ambiguous signature, it can either be an ajax load or attach/fire a "load" event. CCAO cannot tell them apart since it's a dynamic decision based on arguments.

fixes js error for deprecated .load event and replace with .on

---

siteorigin-panels.php

This should fix #505, I've been using it for a while, however I am not 100% sure that this is all that needs to be fixed.
I haven't come accross any other use case though which would break the preview.

Mutliple editors preview fix

---

inc/styles.php

Alternative title: If the background is set but missing, and the post hasn't updated after 2.6.5, notice will appear
If a post previously had a valid background image but the image is no longer available and the post hasn't been updated after installing 2.6.5, there will be a notice output as we try and output the fallback URL without checking if it exists first.
```
( ! ) Notice: Undefined index: background_image_attachment_fallback in C:\wamp64\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\styles.php on line 431
--
1 | 0.0005 | 412400 | {main}( ) | ...\index.php:0
2 | 0.0013 | 412688 | require( 'C:\wamp64\www\siteorigin\wp-blog-header.php' ) | ...\index.php:17
3 | 1.2419 | 17993824 | require_once( 'C:\wamp64\www\siteorigin\wp-includes\template-loader.php' ) | …
```

Fix Background fallback URL notice

---

inc/admin-widget-dialog.php

To resolve siteorigin/so-widgets-bundle#517. Don't show teaser widgets if WB is installed and active.

Remove teaser widgets when WB active

---

css/admin.less

This fixes an issue that Yoast introduced in the latest update where it'll resize the column size fields. This PR also prevents it from happening again because setting a width by default.

Row Cell options: Prevent Yoast from resizing fields

---

js/siteorigin-panels/dialog/row.js
js/siteorigin-panels/dialog/widget.js
js/siteorigin-panels/model/widget.js
js/siteorigin-panels/view/builder.js
js/siteorigin-panels/view/row.js
js/siteorigin-panels/view/widget.js

Resolves https://github.com/siteorigin/siteorigin-panels/issues/541
This PR takes out most/all of the cases where we were triggering events on models that should have been triggered on views. In the future I'd like to have most user events trigger a view action somewhere, but we can tackle that when we actually need it.

View based events

---

inc/admin-dashboard.php

This PR fixes the following notice when running the WooCommerce Setup Wizard.
`Notice: Trying to get property of non-object in C:\wamp64\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\admin-dashboard.php on line 43`
You can rerun the WooCommerce setup by opening a WooCommerce page, and click **Help**. Open the **Setup Wizard** tab and click **Setup Wizard**.

Dashboard Assets: Check if $screen exists

---

inc/widgets/post-loop.php

This PR adds a new filter called `siteorigin_panels_postloop_template_directory`. This filter will allow plugins (and themes with more than two levels deep post template structure) to include their custom post templates.

Post Loop: Add filter to allow for custom template directories

---

inc/admin.php

Layout IDs should use the post ID rather than the revision ID to prevent WordPress from highlighting the ID as a change in the revision browser.
The "Content" section in the revision browser has the wrong layout IDs.
e.g.
The "Page Builder Content" section has things right imo. This uses the current post ID rather than revision ID. The Content section IMO should also use the post ID rather than revision ID. This PR fixes this so things are like this:

Fixed bug with the layout IDs for revisions

---

inc/revisions.php

This PR fixes a bug where a single revision had multiple panel_data objects like this:

Stop duplicate panel_data from being added to wp_postmeta.

---

inc/css-builder.php

Previously it wasn't possible to only specify a `min-width` with `get_css()` (which is used with `add_row_css()`). This PR will allow you to set only a `min-width` by passing a breakpoint of `0:768` (`768 `being the `min-width`).

Get CSS change to allow for only min-width to be set

---

siteorigin-panels.php

To resolve #581 . This just copies the default excerpt functionality, but applies it to the first text type widget found in the first two PB rows.

Auto text widget excerpt

---

inc/admin.php
inc/sidebars-emulator.php

Need to add widgets' `option_` filters earlier and generate and store ids for the emulated sidebar in `save_post` to allow for `is_active_widget` to be checked by widgets when they are registered.

Fix sidebar emulator for Jetpack widgets.

---

js/siteorigin-panels/jquery/setup-builder-widget.js

To fix #573. Should prevent similar issues in future too.

Prevent initializing multiple instances of builder widget dialog.

---

inc/admin.php

[Related Make WordPress Core post](https://make.wordpress.org/core/2018/11/07/meta-box-compatibility-flags/).
This PR will disable the Page Builder meta box for Gutenberg.
Before:
After:

Gutenberg: Set Page Builder Meta Box backwards compatibility flag

---

inc/admin-layouts.php

This PR fixes a bug that prevents private posts and pages from appearing in the clone list.

Clone Layouts - fix to allow for private posts and pages

---

compat/layout-block.php
inc/admin.php

This change prevents the below notice from occurring whenever `SiteOrigin_Panels_Admin::is_admin()` is used when using 4.9.9.
`019 15:45:24 UTC] PHP Notice:  Undefined property: WP_Screen::$is_block_editor in C:\wamp64\www\siteorigin\wp-4-9-9\wp-content\plugins\siteorigin-panels\inc\admin.php on line 118
`
Based on the previous checks, there doesn't appear to be a reliable manner to check for the Gutenberg plugin pre-WordPress 5.0. There doesn't appear to be any issues by letting it pass.

Fix notice when using WP 4.9.9

---

js/styling.js

This PR will prevent the Full Width Stretched Padding row layout from removing the right/left border on rows.

Don't remove left/right border when Full Width Stretch Padding is enabled on row

---

inc/sidebars-emulator.php

The `url_to_postid()` function includes a fairly expensive, uncached, WP query. This can happen on most to all pages with this plugin, which hurts performance significantly.
I spent a little bit of time to see if we could avoid this entirely with a better solution for getting the `$post_id` in this function, one that doesn't involve a query based on the current request URL. I didn't come across any simple changes, but open to ideas on that front.
As a fix for the performance problems here, I've implemented some caching so `url_to_postid()` isn't repeatedly called. This is similar to the helper function we use at WordPress.com VIP: https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/vip-helpers/vip-caching.php#L252-L276

Cache the result of url_to_postid()

---

js/yoast-compat.js

This PR will provide Yoast with all of the images used in the Image Grid and Masonry widgets.
This PR will also provide Yoast with the URL used with Yoast. As with the images, however, it doesn't resolve the link so it won't be enough to resolve the Yoast internal flag unless the user doesn't set the link using the Select Content option.

Pass SiteOrigin Image Grid, Masonry, and Button widget data to Yoast

---

inc/styles.php

This PR adds the ability to set the Background Image Display style setting to [Contain](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#contain).

Add Contain Background Image Display option

---

inc/settings.php

Simple update, adding support for a "password" input type (useful for API keys etc...).

Adding support for "password" field type in settings

---

siteorigin-panels.php

Resolves #680
When installing using TGMPA, the redirect will happen on the next page the user views and not directly after activation.

 Prevent Welcome Page Redirect During Bulk Install and TGMPA

---

siteorigin-panels.php

This PR fixes an issue that prevents custom Read More text from being used.
`$more_link_text` is only set if `$matches[1]` is empty so checking if `$more_link_text` exists will always fail. Checking the contents of `$matches[1]` is enough to determine if a custom read more text is present.

Resolve Read More Custom Text issue

---

readme.txt

Hi,
just had an issue with this plugin and the WordPress Updater, because this plugin says it requires at least WordPress 4.4, but it uses the [wp_doing_ajax](https://github.com/siteorigin/siteorigin-panels/blob/15cbc79ae97aedcf0d33e6b23544bb624a765140/siteorigin-panels.php#L46) function, which was [introduced in WordPress 4.7](https://developer.wordpress.org/reference/functions/wp_doing_ajax/#changelog)
This broke my site and should be preventable by raising the minimum WordPress Version or removing the function. This PR does the easy thing of just raising the minimum WordPress Version.

Raise minimum WordPress version

---

inc/admin.php

The change https://github.com/siteorigin/siteorigin-panels/commit/2a6179a04ac88ce712e49bae6bde7a854b050c54 introduced an issue where widgets that didn't have a dedicated class weren't showing up in Page Builder. This PR fixes that by only using the `$widget_obj` class, when the given `$class` from the array key is a hash.

Add support for widgets that don't have a dedicated class

---

css/admin.less

Resolves #700 and #709.
@AlexGStapleton Please, can you check admin widget title sizing in both the Block and Classic Editor. Do so with one of our themes and Sydney to resolve #700. Thanks.

Set admin widget title font size

---

css/admin.less

Resolves #711.
The new core admin styles have set a `line-height` of `2` to input fields.

Set widget search form line height

---

css/admin.less

Prevent WebKite font size adjustments in the widget modal.
Resolves https://github.com/siteorigin/siteorigin-panels/issues/702.

Prevent WebKit font size adjustments

---

css/admin.less

Resolves https://github.com/siteorigin/siteorigin-panels/issues/716. 
Perhaps there is a better way to achieve superior specificity? `text-decoration: none;` is the only change where I'm not repeating rules. The link color and font family changes are just re-adding rules further down the cascade.

Twenty twenty fixes

---

css/admin.less

**Problem:**
This PR matches the clear button styling we're using in the Hero etc.
Alex, you ok with this or should I try to do this in a more global manner? I'm not really familiar with the overall admin CSS layout so yeah, this is quite a focussed fix. I couldn't immediately see any other buttons like this on the same side panel that needs to be targetted.

Added styling for the bg color clear button

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

In WP 5.4, .editor-writing-flow was renamed to `.block-editor-writing-flow` and an accessibility div with a tabindex was also added. This PR accounts for both and allows for the Add SiteOrigin Layout Block to appear again.
This PR also accounts for backward compatibility by maintaining the previous selector.

Resolve WP 5.4 Add SO Layout Block button not appearing

---

css/admin.less
js/siteorigin-panels/view/live-editor.js
tpl/js-templates.php

Resolve #284
This PR changes the device resolutions in the Live Editor to reflect the global Page Builder Settings. It also prevents the resizing of the preview to allow for accurate previews on devices that use a resolution higher than the one they're previewing.
To prevent the misalignment of the preview at different resolutions and adjusted device widths (if the user changes to a device other than the default), how the preview is displayed had to modified to be closer to rely less on negative margins to account for the Live Editor side. Instead, a calculated width was used instead.

Live editor: Use Global Settings for device widths and prevent scaling

---

siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/755
This PR changes the legacy device detection to include effectively [all versions of IE](https://www.whatismybrowser.com/guides/the-latest-user-agent/internet-explorer). Edge does not include Trident in its user agent so it won't be picked up by this change.

Legacy Layout: Detect IE 11 as legacy browser

---

js/siteorigin-panels/model/widget.js

[Related](https://github.com/siteorigin/so-widgets-bundle/pull/1051#issuecomment-636084170)
This PR will prevent booleans from being used as widget descriptions.

Prevent boolean values from being used as widget description

---

inc/css-builder.php

Related https://github.com/siteorigin/siteorigin-premium/pull/395#issuecomment-635546170
This PR will prevent an issue where the generated CSS will have selectors with no attributes set. It'll prevent the following situation:

CSS Builder: Don't add selectors with no attributes

---

js/siteorigin-panels/view/live-editor.js

This PR resolves https://github.com/siteorigin/siteorigin-panels/issues/757 by setting the Live Editor Iframe src to the current page. Previously a URL [wasn't set due to previewing issues with drafts](https://github.com/siteorigin/siteorigin-panels/commit/778957ac037d1d29de9684a9181caa8055749c54). It appears we've indirectly resolved whatever issue was occurring at the time as I didn't come across any issues with drafts after making this change.

Live Editor: Set preview url for iframe to avoid Chrome issue

---

inc/admin.php
js/seo-compat.js
js/siteorigin-panels/view/builder.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/726
While https://github.com/siteorigin/siteorigin-panels/pull/752 indirectly helped, there were certain widget not being picked up correctly. Widgets such as the Image widget. To verify this PR helps, please add a focus keyword and then add an image with that focus keyword in the alt. In develop, the `Focus Keyword found in image alt attribute(s)` check will never pass.
I went with renaming yoast-compat.js rather than creating a new dedicated rankmath-comat.js file due to the vast amount of code that would need to be repeated.

Add content analysis integration for Rank Math 

---

inc/widgets/layout.php
js/siteorigin-panels/jquery/setup-builder-widget.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/433
Test code:
```
function so_disallow_new_widgets_layout_builder( $supports ) {
$supports['addWidget'] = false;
return $supports;
}
add_filter( 'siteorigin_panels_layout_builder_supports', 'so_disallow_new_widgets_layout_builder' );
```
[Possible options](https://github.com/siteorigin/siteorigin-panels/blob/develop/js/siteorigin-panels/view/builder.js#L45-L58).

Add siteorigin_panels_layout_builder_supports

---

css/admin.less
js/siteorigin-panels/view/builder.js

This PR resolves a few issues with the page builder interface in WP 5.5. 
Fix "undefined" Page Builder tab issue in WP 5.5
Fix "undefined" Page Builder tab issue in WP 5.5. For whatever reason, the span inside of the h2 was removed in WordPress 5.5. Removing the span from the selector resolves this issue and results in no adverse effects in either version of WP.

Fix "undefined" Page Builder tab issue in WP 5.5

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx
compat/layout-block.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/729 Resolve https://github.com/siteorigin/siteorigin-panels/issues/730
Currently, this PR will only show the active SiteOrigin Layout block in the preview.
This PR modifies a Builder JS file so `build:dev` must be run.

Layout Block: Add Support for History and Layout Builder

---

inc/widgets/post-loop.php

Resolves https://github.com/siteorigin/siteorigin-panels/issues/779
This PR allows developers to create custom format pagination links that are specific to the post loop widget.
To test this, please add the following PHP to your post loop:
```
echo paginate_links( array(
'format'       => '?page-' . SiteOrigin_Panels_Widgets_PostLoop::get_current_pagination_id() . '=%#%',
'prev_next'    => false,
) );
```
The above code uses `?` rather than a clean permalink. The plugin/theme developer will need to add custom rewrites for their specific usage to have clean permalinks. This must be done by them rather than us automating as it requires a rewrite flush and that's not something we want to automatically do every time a new post loop is added.

Post Loop: Add custom pagination format support

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

Resolve https://github.com/siteorigin/siteorigin-panels/issues/715
This PR will prevent the user from being able to save the page until Page Builder has loaded the new layouts json and stored it.

Layout Block: Prevent Block Editor Saving until Json loaded

---

css/admin.less

Resolve https://github.com/siteorigin/siteorigin-panels/issues/719
This PR removes the spacing around modals and makes the interface overall fill the device more. It also disables the live editor preview until the editor is collapsed to make the interface more useable.

Modal and Live Editor adjustments

---

css/admin.less

Resolve the sidebar overlap issue on desktop.

Fix right sidebar overlap on desktop

---

inc/settings.php
inc/styles.php
js/siteorigin-parallax.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/158
Requires premium PR: https://github.com/siteorigin/siteorigin-premium/pull/403
The premium is required because it overrides the PB parallax with its own (modified) verison.

Add "Disable Background Parallax On Mobile" Global Setting

---

compat/amp.php
inc/admin.php
siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/737
The AMP plugin overrides the text widget and extends the base text widget class to do this ([reference](https://github.com/ampproject/amp-wp/blob/6935c0c015e52fc58b27c4790348bae56522c875/includes/widgets/class-amp-widget-text.php)). The text widget requires its JS to be directly output so this PR adds the AMP widget as a Core JS widget.

Resolve AMP Editing Issue

---

inc/css-builder.php
inc/styles-admin.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/720
Replaces [esc_html](https://developer.wordpress.org/reference/functions/esc_html/) with [wp_strip_all_tags](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/).

Remove all HTML from CSS Styles and strip slashes from textarea/code style fields

---

js/siteorigin-panels/view/widget.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/703
This PR resolves an issue affecting certain Android devices where the edit widget prompt wouldn't be opened when they touched the widget. Instead, the widget would go into the draggable mode. This PR allows for both the edit widget prompt to open and the widgets to still be draggable.

Android Chrome: Improve edit widget touch detection

---

inc/admin.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/790
Yoast merged all of their editor specific JS files into one general file so our previous script detection failed. This PR accounts for backward compatibility by retaining the previous script check.

Yoast : Resolve 14.6 Integration Issue

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

Uses the suggested compatibility code. Tested using 5.5-RC1-48698 and 5.4.2. Please note that formatting is different in .js due to spaces being stripped by `build:dev`.

Layout Block: Use new Block Categories if WP 5.5

---

js/siteorigin-panels/view/builder.js

This PR prevents a situation where the user views the editor, makes no changes, and then attempts to navigate away. They then get hit with a "are you sure you want to navigate away? There is unsaved data" confirm message. This PR will prevent the post content from being updated on load while still allowing `contentPreview` to be set - which is required for SEO plugins. The post content is set on save so it doesn't need to be set on load but `contentPreview` isn't and needs to be. When the post content is updated on load it triggers a keyup on TinyMCE which will make WordPress (rightfully) think there has been a content change.
I've had a hard time replicating this issue but two users have reported this fix helped.

Prevent Potential Confirm Notice

---

inc/admin.php

Resolves https://github.com/siteorigin/siteorigin-panels/issues/795
This commit prevents an issue where the SO Layout Block may break due to saved data being different.
To test this issue you'll need to have a widget that adds a link with `target="_blank"` set and doesn't set both `noopener` and `noreferrer` (related https://github.com/siteorigin/so-widgets-bundle/pull/1080). Add the widget, set the widget up to add the link and then save. Reload the page and the editor will SiteOrigin Layout Block will Break:
Load this PR and recover the block by clicking the three dots and then selecting `Attempt Block Recovery`. Duplicate a widget/row (this will trigger the block content to update itself) and then remove the duplicate. Save. Reload the editor and the Block will work as expected.

Run wp_targeted_link_rel on the generated preview content

---

compat/yoast-sitemap.php
siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/723
I used DOMDocument rather than regex as Yoast changed from regex to DOMDocument. It appears to be due to reliability issues but I wasn't able to find concrete information on this.

Yoast Sitemap: List images added using Page Builder

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx
compat/layout-block.php
js/styling.js

This PR resolves an issue new [Block Editor Preview Options](https://make.wordpress.org/core/2020/08/04/new-editor-preview-options/) and layouts that contain Row Layouts set to something other than Standard. To replicate this issue please import the Consultant Layout into the Block Editor and change device preview. You'll notice that the length of the rows is larger than the device preview area. This PR triggers a row resize to resolve this issue.

Layout Block: Add Support for new Preview Options

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx
js/seo-compat.js
js/siteorigin-panels/helpers/editor.js
js/siteorigin-panels/main.js
js/siteorigin-panels/view/builder.js

This PR improves the SEO compatibility code for the SiteOrigin Layout Block. It allows for multiple SiteOrigin Layout Blocks to pass changes to SEO Plugins and also resolves a content extraction issue for the SiteOrigin Layout Block that prevented certain widgets from being completely compatible. An example of such a widget is the SiteOrigin Block Editor widget where the Destination Link setting wasn't being picked up correctly.
This is quite a large change with a lot of moving parts so thorough testing is required. This PR must also be tested using either `build:dev` or `build:release` as editor JS files were modified.

Improve Block Editor SEO Compatibility Support

---

js/seo-compat.js

This PR resolves the below error message. This error can prevent `contentModification` from being run. This can result in situations where blank empty widgets are included in the content analysis ([related](https://siteorigin.com/thread/yoast-compatability-issue/)).
I've run some tests using older versions of Yoast and this PR still applies.

Yoast SEO Compat: Wait until Yoast is ready

---

settings/admin-settings.js

[Related](https://github.com/siteorigin/so-widgets-bundle/pull/1129)
This PR prevents the Enable jQuery Migrate Helper plugin from triggering a warning when viewing **WP Admin > Settings > Page Builder**.

Prevent jQuery migrate notice on settings page

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

This PR resolve the following Yoast Notice while using the Block Editor:
This change doesn't affect the Classic Editor so it's not related to https://github.com/siteorigin/siteorigin-panels/issues/811.

SiteOrigin Layout Yoast Compat: Always pass builderView

---

js/seo-compat.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/811
window.soPanelsBuilderView will always be set when using the Classic Editor so the compatibility code will always run. This is fine in the Block Editor, but it runs into issues with the Classic Editor. This PR is set up to only run the Compatability code when PB is enabled or the SiteOrigin Layout is present.

SEO Compat: Ensure PB is enabled before running compatibility code

---

js/siteorigin-panels/dialog/prebuilt.js

This PR is a follow up to https://github.com/siteorigin/siteorigin-panels/pull/800
wp.data can be loaded in the Classic Editor by other plugins so it can't be relied on. This PR checks the body class for a Block Editor specific class as that will only ever be added if it's the block editor.

Layout Export: Correctly detect Block Editor

---

inc/admin-layouts.php

We're in a situation where we would like to add a simple "Favorites" filter to the layouts response - so only posts with a certain meta data will be shown - but there is no way for us to hook in and do this.
One way to allow this is to add an option for early opt-in to take over the results (an `if` condition before the [prebuilt condition](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/admin-layouts.php#L198)?)
But we can also achieve the same results if we get a filter for the final response and I feel like this - in general - is just a good addition to developers. So for now this would be my "I hope they accept it quickly" suggestion as seen in the PR :relaxed:
Best regards

Add Layouts AJAX response filter

---

inc/admin.php

[Reported here](https://siteorigin.com/thread/color-picker-not-working/)
This will prevent the colour field from appearing as a text field if no other plugin loads the WordPress Color picker. The color picker was added in WordPress 3.5 and is a dependecy of the SiteOrigin Widgets Bundle so backwards compatability isn't a major concern.

Add wp-color-picker as editor dependency

---

inc/admin.php
js/siteorigin-panels/view/builder.js
tpl/metabox-panels.php

This PR sets contentPreview on load to prevent a Rankmath sometimes not picking up on the page builder layout on load.

SEO: Set ContentPreview on load

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

This PR will prevent potential JavaScript conflicts due to variables being generic. You can test this PR by installing [Smart Logo Showcase](https://wordpress.org/plugins/smart-logo-showcase-lite/) and opening a page using the Block Editor.
As this change renames a bunch of varibles it's possible any number of things could break so a general run-through of the page builder interface should be done to ensure no issues have arisen.

Layout Block: Avoid potential JS Conflicts

---

js/seo-compat.js

This PR removes elements that have no direct content analysis value. For example, there's no reason to include a slimmed down version of any inline JavaScript as search engines ignore it.
This PR also avoids an issue with iframes that prevent the full Rank Math interface from showing. When an iframe is added, an error occurs and that prevents [this part](https://i.imgur.com/qrCvv7D.png) of the Rank Math interface from showing. The easist way to trigger this issue is to add a YouTube URL to a SiteOrigin Editor widget.

SEO: Remove elements that have no content analysis value

---

inc/admin.php
tpl/metabox-panels.php

This resolves a Live Editor preview issue when there's a loop present on the page.
This should also resolve the following error message (although I haven't been able to replicate this error):
`An error of type E_ERROR was caused in line 6 of the file /srv/htdocs/wp-content/plugins/siteorigin-panels/tpl/metabox-panels.php. Error message: Uncaught Error: Call to undefined method SiteOrigin_Panels_Admin::generate_panels_preview() in /srv/htdocs/wp-content/plugins/siteorigin-panels/tpl/metabox-panels.php:6`

Generate preview_url before preview_content

---

js/siteorigin-panels/view/builder.js

This PR updates the depreciated jQuery Bind instance. Please note that the other usage of bind, such as `.bind( this )`, is using native JS ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)).

Update Depreciated jQuery Bind Usage

---

inc/widget-shortcode.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/888
[JSON_UNESCAPED_UNICODE PHP.net Reference](https://www.php.net/manual/en/json.constants.php#constant.json-unescaped-unicode)
This will prevent an issue where certain languages, such as Greek, would be encoded and be unsearchable. Here's the test string I'm using:
`Αυτό το κείμενο χρησιμοποιείται για τη δοκιμή ενός ζητήματος που σχετίζεται με το γραφικό στοιχείο της δυνατότητας SiteOrigin.`
This PR is not retroactive so after switching to this branch you'll need to make a change to the page (Copy Content won't be triggered if no change is detected) for the updated text to be stored.

Copy Content: Encode Multibyte Unicode Characters Literally

---

inc/css-builder.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/838
This PR resolves a deprecated notice while using PHP 8. `$sub_selector` is meant to be optional but it previously wasn't set as one.
[25-Dec-2020 11:27:47 UTC] PHP Deprecated:  Required parameter $sub_selector follows optional parameter $ri in C:\Users\Alex S\Local Beta Sites\siteorigin\app\public\wp-content\plugins\siteorigin-panels\inc\css-builder.php on line 157

CSS Builder Resolve PHP 8 Notice

---

inc/renderer.php
inc/settings.php

Related https://siteorigin.com/thread/having-issue-with-page-builder-layout-css-output/
The CSS Output Location setting isn't compatible with the Block Editor in a reliable manner - it's rare that it does work. This PR will limit this setting to the Block Editor and add it mentions this limitation in the description in the CSS Output Location description.

Limit CSS Output Location Setting to Classic Editor

---

inc/admin.php

This PR will prevent a situation where the SiteOrigin Layout will attempt to render an empty block. This situation should rarely happen after https://github.com/siteorigin/siteorigin-panels/pull/837 but if the user clicks fast enough they can force it.
`[25-Dec-2020 11:40:49 UTC] PHP Warning:  Undefined array key "panelsData" in C:\Users\Alex S\Local Beta Sites\siteorigin\app\public\wp-content\plugins\siteorigin-panels\inc\admin.php on line 1206`

SiteOrigin Layout: Don't Attempt to Render Empty Layout

---

inc/admin-layouts.php
inc/admin.php
inc/css-builder.php
inc/post-content-filters.php
inc/renderer-legacy.php
inc/renderer.php
inc/settings.php
inc/sidebars-emulator.php
inc/styles-admin.php
inc/styles.php
inc/widgets/post-loop.php
widgets/widgets.php

This PR replace PHP 4 type conversion functions with type casts. [This is in line with WordPress 5.6](https://core.trac.wordpress.org/ticket/42918) and there's a slight performance improvement.
`intval()` replaced with `(int)`
`strval()` replaced with `(string)`
`floatval()` replaced with `(float)`
lessc uses `floatval()` but it was not modified.

Replace older-style PHP type conversion functions with type casts.

---

compat/acf-widgets.php
compat/js/acf-widgets.js
inc/admin.php

This PR adds compatibility for widget fields added by ACF inside of the Page Builder interface. A new action is introduced in this PR called `siteorigin_panels_before_widget_form`. This action is triggered before the widget form is output.
[Test Fields](https://drive.google.com/uc?id=1hFP7XFQcQmX4zt7ZmGT1uGsyKfI26jfN) (to import, navigate to **Custom Fields > Tools**)

ACF Widgets Fields Compatibility

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

This PR will prevent the SiteOrigin Layout Preview button from appearing when in edit mode if there's no panelsData. It'll also reset the panelsData if the user removes all rows from the SiteOrigin Layout to prevent the preview (no longer valid) preview from showing.
This change also prevents a previewing error that commonly occurs while using PHP 8. When using PHP 8, when the SiteOrigin Layout triggers an update to the server and you're in editing mode, clicking the block preview won't do anything - a second click after the preview has loaded is required to view it. Normally it switches to preview mode and adds a loading indicator.
This PR can be triggered by adding a SiteOrigin Layout Block. The preview won't appear. Add a widget and it'll appear. Remove it, and it'll disappear.

Layout Block: Hide preview button when no preview is available

---

css/admin.less

Allow Layout Title to Extend Panel Height

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx

Resolve duplicate SO Layout Button in WordPress 5.7:
Note: The selectors needed for this button are too long to do on a single line or I would have used a ternary. A build will be required for this change to be visible.

WP 5.7: Prevent duplicate Add SO Layout button

---

inc/sidebars-emulator.php

This PR changes how the Sidebar Emulator detects the current page id. Instead of detecting based on the entire URL it detects it based on the path.
This change was done to resolve a WPML compatibility issue - [details here](https://wpml.org/errata/page-builder-by-siteorigin-pagination-does-not-work-in-the-blog-page/).

Sidebar Emulator: Detect Page ID by path

---

compat/lazy-load-backgrounds.php
compat/lazyload-backgrounds.php
siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/850
This PR allows for plugins/themes that add [LazyLoad](https://github.com/verlok/vanilla-lazyload) to be able to lazy load row, cell, and widget backgrounds. Backgrounds set to parallax will not be lazy loaded.
To this please install [Lazy Load](https://wordpress.org/plugins/rocket-lazy-load/)
Once installed please navigate to **Settings > LazyLoad** and enable **Images**.
Filters:
Enable Lazy Load Compat if Lazy Load plugin isn't installed.:
`add_filter( 'siteorigin_lazy_load_compat', '__return_true' );`
Inline Background Image (requires first snippet if LazyLoad plugin isn't enabled):
`add_filter( 'siteorigin_lazy_load_inline_background', '__return_true' );`
You can test the second snippet while lazy loading is enabled by …

Lazy Load Compat

---

inc/styles-admin.php

This PR resolves an issue where the remove button will always appear for row/cell/widget background images regardless of whether an image was set or not.

Styles Background Image: Typecast when checking image

---

compat/js/siteorigin-panels-layout-block.js
css/admin.less
inc/styles-admin.php
js/siteorigin-panels/dialog/history.js
js/siteorigin-panels/dialog/prebuilt.js
js/siteorigin-panels/dialog/row.js
js/siteorigin-panels/dialog/widget.js
js/siteorigin-panels/dialog/widgets.js
js/siteorigin-panels/helpers/accessibility.js
js/siteorigin-panels/main.js
js/siteorigin-panels/view/builder.js
js/siteorigin-panels/view/dialog.js
js/siteorigin-panels/view/live-editor.js
js/siteorigin-panels/view/styles.js
js/siteorigin-panels/view/widget.js
tpl/js-templates.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/765
Status (pending approval):
Note:
- There's no way to reorder widgets or rows. This needs further investigation and will be implemented in a future PR.

Improve Page Builder Interface accessibility

---

css/admin.less

Fixes a situation where the Add Layout button may be larger than expected.

Remove Add Layout button height: 100% to avoid sizing issue

---

inc/admin-layouts.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/853
This PR resolves an issue caused by using .json files with [the proper JSON MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) instead of a text mime type. This issue resulted in the layout being committed from the prebuilt layout list.

Prebuilt Layouts: Check for JSON MIME

---

siteorigin-panels.php

This PR adds support for the more quicktag. It doesn't however add support for custom more text as automatic WP excerpts don't allow for HTML. Prior to this PR the more quicktag would be ignored.

Automatic Excerpt: Add Support for Excerpt

---

siteorigin-panels.php

This PR extends the automatic excerpt generation to support the Block Editor. The first block has to be a SiteOrigin Layout Block for the content to be extracted.

Automatic Excerpt: Add Support for Block Editor

---

inc/renderer.php

This PR prevents pages from processing twice if the previous page was the same as the current one. When this happens, an error is logged in the error_log, and the renderer fails silently.
[Here's a test plugin](https://drive.google.com/uc?id=14pfrGVuVZ6_Mj4-JmP1oZowIpJOB1w_e). Once installed, add [so_test] to any page that you want to test the PR against. Please note that while this PR isn't active, the page won't work nor will it be editable due to an infinite loop.
This commit adds `siteorigin_panels_renderer_current_post_check` filter to prevent this check. Here's a snippet to test that filter:
`add_filter( 'siteorigin_panels_renderer_current_post_check', '__return_true' );`

Prevent repeated potential rendering of PB Layouts

---

inc/styles.php

This PR is in response to https://wordpress.org/support/topic/fiexed-backgrounds-dissapear-after-upgrading-2-12-0/
The user had a background, an external background, and a background color set so it would always fail this check.

Correctly ensure either Background, or fallback is set

---

inc/admin.php
tpl/metabox-panels.php

This PR will move the PHP outside of the Metabox template into the admin.php file. It also resolves https://github.com/siteorigin/siteorigin-premium/issues/506

Move PB Metabox PHP Outside of Template

---

inc/admin.php
siteorigin-panels.php

The change in siteorigin-panels.php will prevent a potential fatal error on WP pre-5.0 websites.
The change in admin.php is a precautionary change as that line won't result in an error, but there is a small possibility it may trigger one regardless.

Add checks for has_blocks() before using it

---

inc/admin.php

This PR will prevent an error for those using versions of ACF older than 5.7.10. Version based on [this changelog](https://www.advancedcustomfields.com/blog/acf-5-7-10-release/). It will however mean that the user won't be able to use ACF in widgets.
```
An error of type E_ERROR was caused in line 69 of the file
/home/**/public_html/rhpic/wp-content/plugins/siteorigin-panels/compat/acf-widgets.php.
```

ACF: Ensure at least version 5.7.10 is being used before loading compat

---

compat/lazy-load-backgrounds.php
siteorigin-panels.php

This PR adds support for the main WP Rocket plugin's Lazy Load.
- DONOTROCKETOPTIMIZE will be set by WP Rocket (or a developer) if the current context doesn't allow for optimization. By default, this happens when logged into an account so you'll need to either enable optimizations for logged in users or view the page while logged out for the background to lazy load.
- The `do_rocket_lazyload` filter is the method recommended by WP Rocket for disabling Lazy Load on a page by page basis.

Lazy Load: Add Support for Main WP Rocket Plugin

---

js/siteorigin-panels/view/styles.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/159
This PR allows developers to filter fields based on the widget the user is editing. This is done using the pre-existing `siteorigin_panels_widget_style_fields` filter.
The following test snippet will remove the Widget ID widget from the WordPress Archives widget.
```
add_filter( 'siteorigin_panels_widget_style_fields', function( $fields, $post_id, $args ) {
if ( isset( $args['widget'] ) && $args['widget'] == 'WP_Widget_Archives' ) {
unset( $fields['id'] );
}
return $fields;
}, 10, 3 );
```

Widget Styles: Pass Widget To Server

---

inc/renderer.php
inc/styles-admin.php
inc/styles.php

Ability to create an individual rows collapse point. 
This allows rows to collapse at individual values vs having to use the mobile collapse point that is set. If no value is set for the row it will use the mobile collapse point as a default value. 
An additional "number" field type is also added to the available admin field types.
Edit: This PR adds the `siteorigin_panels_css_row_collapse_point` filter. This allows you to override the collapse point of a row on a row by row basis.
The following test snippet will add a setting called "Row Collapse Point" to the Row Styles Layout settings group. This will allow you to confirm this setting works without needing to use code:
```
// Add in collapse point input field.
add_filter( 'siteorigin_panels_row_style_fields', function( $fields ) { …
```

Individual row collapse value

---

inc/renderer.php

To test, enable the PB Tablet Layout setting and then add a four-column row. If it collapses as expected, it worked. You can test that the collapse point filter still works as expected by using the snippet in [the initial PR](https://github.com/siteorigin/siteorigin-panels/pull/873).

Prevent Collapse Point From Preventing Tablet Row Collapse

---

css/front-flex.less
css/front-legacy.less

Resolve https://github.com/siteorigin/siteorigin-panels/issues/885
To test this please right-click a modern parallax that's using an image that larger than the area it's applied too , and disable the inline `overflow: hidden;`. If the parallax doesn't exceed the row/widget the CSS works as expected.

Modern Parallax: Prevent Overflow Using CSS

---

inc/styles.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/879
This will ensure any local images have the following attributes set:
- srcset
- sizes
- alt (if applicable)
- title (if applicable)
- loading

Modern Parallax: Use Image attachment if possible

---

compat/js/acf-widgets.js

This PR will prevent a situation where fields that have special JS associated with them (such as the Image field) aren't always detected.
To test this PR please follow these steps:
- Add an Image field to Widgets.
- Open any Page Builder powered page and add an archives widget.
- Open the Archives widget and set an Image
- Save, and reload.
- Open the Archives widget and attempt to change the Image.
Prior to This PR, you may or may not be able to edit the image. How often it previously worked appears to be related to server performance and/or how fast you open the widget;

ACF Compat: Use `panelsopen` for more consistent loading

---

compat/acf-widgets.php

This PR resolves the following notice when opening widgets with widgets with ACF data without values set.
``[08-Jun-2021 14:31:59 UTC] PHP Warning:  Undefined array key "acf" in /Users/**/Sites/siteorigin/wp-content/plugins/siteorigin-panels/compat/acf-widgets.php on line 55``

ACF Compat: Ensure Instance ACF data exists

---

css/admin.less

The toolbar icons are a little out of alignment in the Live Editor, this PR adjusts the padding for the Live Editor.

Adjust the tool button padding for the Live Editor

---

js/siteorigin-panels/dialog/row.js

[Reported here](https://siteorigin.com/thread/default-column-count-editor-add-new-row/)
This PR will prevent PB from overriding the default Row Values.
Test snippet:
```
add_filter( 'siteorigin_panels_row_column_count_input', function( $input ) { 
return '<input type="number" min="1" max="12" name="cells" class="so-row-field" value="4" />';
} );
```
This will change the default column count to 4.

Don't Override Default Row Values

---

inc/admin.php
js/siteorigin-panels/dialog/row.js
js/siteorigin-panels/view/builder.js

[Requested here](https://github.com/siteorigin/siteorigin-panels/pull/888#issuecomment-860242510)
This PR adds a PR that allows you to change the default row columns. For example, the following snippet will change the default row columns to 3 rows with 33.33% width each.
```
add_filter( 'siteorigin_panels_default_row_columns', function( $default_columns ) {
return array(
array(
'weight' => 0.333,
),
array(
'weight' => 0.333,
),
array(
'weight' => 0.333,
),
);
} );
```

Add `siteorigin_panels_default_row_columns` to Allow Overriding default Row Columns

---

inc/renderer.php

This PR will resolve an issue in the live editor (or if the user were to add a `style` element using the [siteorigin_panels_inside_cell_after](https://siteorigin.com/docs/page-builder/hooks/html/#heading-inside-cells-before-and-after ) filter) which results in the bottom margin not being removed. This happens due to certain widgets, such as the SIteOrigin Hero, or SiteOrigin Button, loading adding their custom styling using a `style` element rather than the typical stylesheet. This prevents `.so-panel:last-child` from working as expected.
This issue will affect all layouts, but the easiest way to test it is to import the Staggered Prebuilt layout due to how obvious the gap is in the Live Editor when compared to the normal page.

Live Editor: Resolve Bottom Margin Not Being Removed From Last Widget

---

inc/settings.php

This PR to prevent a situation where legacy isn't used after upgrading, and to avoid a potential override.
A user reported that their parallax had unexpectedly changed after an upgrade and it was due to the parallax being set to modern. This PR implements further checks to prevent that and to prevent a potential setting overridden.
You can test this PR by clearing certain settings.
**To test the override prevention** is working, add the following to [this line](https://github.com/siteorigin/siteorigin-panels/blob/afc61d9fa72b0ce9468fdb27268b4feb2efae9f8/inc/settings.php#L137):
`var_dump( $parallax_type );`
`parallax-type` will be will always equal to exactly the same value you have parallax-type set to so change the parallax type via the settings a few times to ensure this variable is …

Parallax Type: Re-do default value detection

---

js/siteorigin-panels/main.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/894
At least partially related https://github.com/siteorigin/siteorigin-panels/issues/846. The new changes implemented in 5.6 is resulting in this notice appearing and this PR will prevent us from always failing the check.
- Create a build
- Open any Page Builder page and wait a few seconds after the page has finished loading.
- Refresh the page.
Please note that this PR will require a build to be created to be tested.

Prevent undesired "restore content" prompt

---

js/siteorigin-panels/model/widget.js

This PR allows for fields in repeaters and selector to be checked for potential titles, and it allows widgets to have a set field to check for - if set, PB will only check for that value and if it's not set, it'll use the description.
Documentation: https://github.com/siteorigin/docs/pull/119
[Test layout](https://drive.google.com/uc?id=1g1UMVNDr7t-HlGfz7FJq-mma8YOg1smQ)
Open wp-content/plugins/so-widgets-bundle/widgets/button/button.php and find [this section](https://github.com/siteorigin/so-widgets-bundle/blob/1.21.0/widgets/button/button.php#L16-L19). Replace with:
```
array(
'description' => __('A powerful yet simple button widget for your sidebars or Page Builder pages.', 'so-widgets-bundle'),
'help' => 'https://siteorigin.com/widgets-bundle/button-widget-documentation/', …
```

Panel Titles: Check subfields for titles and allow specific field check

---

inc/widgets/layout.php

Requires https://github.com/siteorigin/so-widgets-bundle/pull/1362
This PR prevent WB from including page ids in file names. Pre-existing layout builders don't need to be re-saved.

Layout Builder: Add Builder Instance data to widgets

---

inc/styles-admin.php

It seemed useful to have a class name that can be used to modify the various style fields that appear. Unfortunately I haven't yet worked out how to hook into the 'open_dialog_complete' event that is triggered once the dialog has opened.

Add identifiers to style fields to allow future UI customisation

---

compat/layout-block.php
css/admin.less
inc/admin.php
inc/widgets/layout.php
inc/widgets/post-content.php
inc/widgets/post-loop.php

This PR:
- Allows the Layout Builder to be edited.
Previously an error message stating that the widget must be edited via an admin interface would be displayed.
- Changes how the Layout Builder `panels_data` is loaded to resolve an incompatibility with new widgets rendering.
This change is in line with how the WB Builder field handles data so PB is set up to handle this sort of usage already.
This change that the Layout Builder needs to be tested (specifically, the act of loading page builder data after a save) in the old Widgets interface, new widgets interface, SiteOrigin Layouts Block and full SiteOrigin Page Builder interface. This change also needs to be tested on pre-WP 5.8.
To test this change, add a Layout Builder, and add any widget to the Layout Builder. Save. Reload the editor …

5.8 New Widgets Interface Compatibility Changes

---

compat/layout-block.php

To test this PR please open the 5.8 widget area while WP_DEBUG_LOG is enabled.
`( ! ) Notice: wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.) in C:\Users\Alex\Documents\local-sites\wp-nightly\app\public\wp-includes\functions.php on line 5535`

SO Layouts Block: 5.8 Widgets Area Notice FIx

---

inc/styles.php

Jetpack Image Accelerator (Photon) can result in the parallax being incorrectly sized so this PR will exclude the image. To test this PR:
- Enable Photon (must be on a web-accessible server) by navigating to **Jetpack > Settings**, open the **Performance** tab, and tick "Speed up image load times".
- Ensure Parallax Type is set to Modern.
- Add a Parallax to a row/widget and then save.
- Check the resulting output of the page to ensure the image isn't being served locally and not from wp.com.

Jetpack Image Accelerator: Exclude Modern Parallax Images

---

js/styling.js

This PR resolves a sizing issue while using the Modern Parallax and pressing the browser "back" button. Steps to replicate:
- Navigate to a page with a Modern Parallax image that's larger than the area it's applied too (this isn't a requirement, it just makes this issue really obvious)
- Navigate to any other page.
- Press the browser back button
- Note the image isn't parallax and significantly larger than it should be.
- Switch to branch and reload the page.
- Navigate away and press the browser back button again.
- Confirm Image is parallaxing and sized as expected.

Modern Parallax: Resolve "back" Causing Image Not to Parallax

---

compat/yoast.php
siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/679 & Ninja Form reCAPTCHA error.
When a meta description isn't set, Yoast will render a version of the page to generate the excerpt using `get_the_excerpt`. This is the correct way of doing this, but it can be problematic when plugins account for situations where their plugin is rendered multiple times this which Forminator and Ninja Form both do . This is also compounded by the fact that Page Builder will override `the_content` to replace the fallback content with the generated page builder layout. This PR resolves this entire issue by selectively disabling Page Builder when Yoast is generating the OpenGraph meta description.
To test this PR please set up Forminator form as outlined in #679. Ninja Forms can also be tested …

Yoast OpenGraph: Bypass PB As Needed To Improve Compatibility

---

compat/layout-block.php
inc/admin.php

This PR will resolve the following notice:
`PHP Warning: Cannot modify header information - headers already sent by (output started at C:\Xampp\htdocs\idee\wp-content\plugins\siteorigin-panels\tpl\js-templates.php:113) in C:\Xampp\htdocs\idee\wp-admin\customize.php on line 126`
Please test (regardless of being able to replicate the above issue) the following things:
- The SiteOrigin Layout Block works in the new Widget Area and Customizer.
- The Layout Builder works as expected in the Widget Area and Customizer.

Customizer: Resolve New Widget Area Notice

---

compat/yoast.php

This PR will resolve the following error for users using older versions of Yoast (< 2019):
`Uncaught Error: Call to undefined method WPSEO_Options::get()`

Yoast OpenGraph Compat: Add Additional Compatibility check

---

js/siteorigin-panels/view/styles.js

This JS event allows other developers to set up their custom fields.

Styles Admin: setup_style_fields JS Event

---

compat/polylang.php
siteorigin-panels.php

[Reported here](https://siteorigin.com/thread/the-template-isnt-duplicated-when-uising-polylang/).
Include `panels_data` when duplicating pages.

Polylang Compat

---

inc/styles.php

This PR adds the Links Hover Color setting. Previously, when a user altered the link color, the color wouldn't change on hover and this setting will avoid that situation by allowing them to also set the Links Hover Color.
Links Hover Color is not tied to any setting and can be set independently to the Links Color setting. There are widgets that will have more specific CSS than this setting, and there's no way of really getting around that without potential display issues.

Links Hover Color

---

js/siteorigin-panels/dialog/history.js
js/siteorigin-panels/main.js
js/siteorigin-panels/view/builder.js
tpl/js-templates.php

This will prevent a potential situation where the URL may be incorrect.

History: Use Central Preview URL

---

inc/renderer.php
inc/settings.php
inc/styles.php
js/styling.js
siteorigin-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/866
This PR introduces the two filters outlined in the initial PR. It no longer includes settings as it has been decided this change is a little bit too tricky to manage without assistance. To test this PR please configure the 
`siteorigin_panels_theme_container_width` filter (int) and `siteorigin_panels_theme_container_selector` (CSS selector). For example, here's a snippet for Corp:
```
add_filter( 'siteorigin_panels_theme_container_width', function( $container ) {
return '1170px';
} );
add_filter( 'siteorigin_panels_theme_container_selector', function( $selector ) {
return '.site-content .corp-container';
} );
```
To test this please add four rows with each of the row layouts selected and confirm:
- Standard row is the …

(Optional) Container Breaker Using CSS Rather Than JS

---

inc/admin.php
inc/settings.php
js/siteorigin-panels/main.js
js/siteorigin-panels/view/builder.js
js/siteorigin-panels/view/live-editor.js
settings/admin-settings.js
tpl/metabox-panels.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/359
Workflow:
- User Views page and click Live Editor Quick Link.
- User decides against editing, and clicks close OR user makes edits and then clicks Update to Save Changes
- Live Editor is closed.
New Setting added after the Live Editor Quick Link setting.
Live Editor Quick Link: Close After Editing
Requires Live Editor Quick Link to be enabled to be visible.
If the user upgrades from an older version, the Live Editor Quick Link: Close After Editing setting will be disabled to prevent a potential disruption for existing users. New installs will have it enabled by default.
To test this:
- Open the Live Editor via the Quick Link, make a change, and then click Update.
- Open the Live Editor via the Quick Link, and click Close. …

Live Editor Quick Link: Close After Editing & Improve Update Triggering

---

compat/js/siteorigin-panels-layout-block.jsx

This PR will restore the Live Editor and History buttons for the SIteOrigin Layouts block.
To test this PR you'll need to make a build.

Layout Block: Restore Live Editor & History

---

inc/styles.php

This will prevent rows from being stretched by default. To test this, add a multi-column row and apply a background to one of the cells. Add widgets to the column without the background and then save. The cell with the background will be the full height. Switch to this PR and the cell will be sized normally.

Restore .panel-no-style alignment

---

css/front-flex.less

This PR will prevent a jump that can occur on load that can still result in a CLS being triggered. There's no reason for this CSS to be used when the CSS container Breaker is used so this prevents it. It doesn't remove the body class as someone could be using that.

CSS Container Breaker: Don't add Container Breaker pre-JS CSS

---

js/siteorigin-panels/view/builder.js

This PR will prevent a 404 that can occur when creating a new page using the Block Editor. Basically, Block Editor auto drafts aren't able to be viewed until converted to a draft so this PR will force the page to be saved as a draft before allowing access to the Live Editor.
- Create a new block editor page (don't save)
- Quickly add a SiteOrigin Layouts Block and Archives widget
- Open the Live Editor
Prior to this PR, the above steps will result in a 404 when the Live Editor displays the preview. After switching to this branch the Live Editor simply won't be accessible (due to the Live Editor Button not being visible) until the page able to be viewed.
This PR modifies core PB JS files so a build is required.

Layouts Block: Force Draft Before Allowing Live Editor

---

inc/admin.php

This PR allows you to set a custom link location by adding `%link%` where you would like to output the link and by setting the link anchor using a dedicated `anchor` array. For example:
```
array(
'text' => __( '%link% Use Page Builder to create custom templates for the Product, Archives, Shop, Cart, Checkout, Thank You, and My Account pages', 'siteorigin-panels' ),
'url' => SiteOrigin_Panels::premium_url( 'plugin/woocommerce-templates' ),
'anchor' => __( 'Get the WooCommerce Template Builder Addon', 'siteorigin-panels' ),
),
```
To test this PR, replace all of the `$links` (defined just above the edited section) with the following PHP:
```
$links = array(
array(
'text' => __( 'Get an Accordion Addon for SiteOrigin Widgets', 'siteorigin-panels' ),
'url' => SiteOrigin_Panels::premium_url( …
```

Addon Links: Allow Custom Link Location

---

js/siteorigin-panels/dialog/row.js

This PR will require a build to test.
To test:
- Open a row
- Select a cell
- Change any cell style.
- Save the row.
Prior to this PR, an error would occur. After this PR, no error will occur and it'll save as expected.

Cells: Fix Undefined `style` error

---

js/siteorigin-panels/dialog/row.js

[Reported here](https://wordpress.org/support/topic/changing-the-number-of-columns-when-editing-a-row-will-reset-the-style/)
To test this, please follow the user-provided steps to replicate this:
```
1) Click "Add Row" button to add a row.
2) Open the "Edit Row" window and add Row Class to "Row Styles".
3) Click on the left column area and close the pop-up window by clicking on the "Done" button while "Cell 1 Style" is displayed on the right.
4) Open "Edit Row" again and check Row Class in "Row Styles", and you will see that the class name you set is gone.
```
You'll need to do a build and add a new row upon switching to this branch as this fix isn't retroactive.

Prevent Row/Cell Styles Data Mismatch

---

js/siteorigin-panels/view/row.js
js/siteorigin-panels/view/widget.js

[Reported here](https://wordpress.org/support/topic/disabled-fields-js-error-cant-access-property-disable_widget/)
To test this PR, add the following code snippet to remove all Widget Styles:
```
add_filter( 'siteorigin_panels_widget_style_fields', function($fields) {
$fields = [];
return $fields;
}, 1000 );
```
Now open any widget, and check the console for the following error (line numbers may differ):
> Uncaught TypeError: can't access property "disable_widget", e is undefined in siteorigin-panels.min.js:8:68283
Once you switch to this PR, this notice won't occur.

Widget/row Styles Removed Undefined Notice

---

inc/admin.php
js/siteorigin-panels/model/widget.js

This PR will allow for widgets with a predefined panels_title to check sub fields. This allows for a situation where the repeater is set by the first valid instance in a repeater. To enable this, you need to set `panels_title_check_sub_fields` to `true`.
To test this PR, open widgets/features/features.php and find:
`'help'         => 'https://siteorigin.com/widgets-bundle/features-widget-documentation/',`
Add to the next line:
`'panels_title' => 'icon_title',
'panels_title_check_sub_fields' => true,`
Now add a Features widget to a page, add a feature, and set an Icon Title. Note that the description isn't updated.
Save, and then switch to this PR. You'll now note that the `icon_title` is picked up.
Please ensure standard `panel_title` works as expected by adding the Editor and updating …

Add `panels_title_check_sub_fields` to Allow for Sub Field Detection

---

inc/renderer.php
inc/settings.php

Requested [here](https://github.com/siteorigin/siteorigin-panels/issues/931#issuecomment-946540772) and [here](https://wordpress.org/support/topic/new-setting-request/).
This PR Adds the `Widget Mobile Bottom Margin` setting which controls the default widget bottom margin for widgets. This setting is overridden by the `Widget Mobile Margin` setting.

Add Global Setting: Widget Mobile Bottom Margin

---

inc/renderer.php
inc/settings.php
inc/styles.php

[Requested here](https://wordpress.org/support/topic/new-setting-request/)
This PR adds a new global setting that acts as a default for the `Mobile Cell Margins` row setting. The default value is 30px and if the user upgraded, the default changes to the same value as the `Row/Widget Bottom Margin` setting.
- Firstly, set a non-standard `Row/Widget Bottom Margin` value (something other than 30). As that'll allow you to confirm the `Mobile Cell Margins` default is correctly set based on that.
- Add a two rows with two columns each. Add an archive widget to column.
- Open the first row in the editor and go over to the Row Styles sidebar. Open the Mobile Layout settings group and set the Mobile Cell Margin setting to anything but the default (or blank).
- Save, and view the …

Add Mobile Cell Margins Seting

---

js/siteorigin-panels/main.js
js/siteorigin-panels/model/widget.js

This PR will resolve a jQuery Migrate notice and potential error in newer versions of WordPress.
`ready event is deprecated Plugin: Page Builder by SiteOrigin `

jQuery `ready` Compatibility Fix

---

widgets/lib/lessc.inc.php

Resolves the following fatal errors when using the Page Builder Legacy Widgets:
```
( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\Users\Alex S\Local Sites\so\app\public\wp-content\plugins\siteorigin-panels\widgets\lib\lessc.inc.php on line 657
( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\Users\Alex S\Local Sites\so\app\public\wp-content\plugins\siteorigin-panels\widgets\lib\lessc.inc.php on line 1624
( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\Users\Alex S\Local Sites\so\app\public\wp-content\plugins\siteorigin-panels\widgets\lib\lessc.inc.php on line 2281
( ! ) Fatal error: Array and string offset access syntax …
```

PHP 8 lessc.inc.php Fixes

---

js/siteorigin-panels/view/builder.js

This PR will resolve an issue that prevents the row re-ordering from working as expected. It resulted in a loss of styling and the row being incorrectly positioned making re-ordering really tricky to do. This issue was introduced in the updated jQuery UI Sortable update in 5.9.

WP 5.9 Compat: Account for updated jQuery UI Sortable appendTo change

---

inc/renderer.php
siteorigin-panels.php

This PR will ensure only pages with non-standard row layouts have the theme container removed.

CSS Container Breaker: Only Remove Containers `max-width` on Pages With Non-Standard Row Layouts

---

widgets/lib/lessc.inc.php

This PR resolves the following error:
`Fatal error: Call to undefined method lessc_parser::buffer() in /wp-content/plugins/siteorigin-panels/widgets/lib/lessc.inc.php on line 3065`
`strlen` (a standard PHP function) does everything buffer does and it's _always_ present (introduced in PHP 4).

Legacy Widgets: Resolve lessc.inc.php error

---

widgets/lib/lessc.inc.php

It's possible for the $count to be wrong, and this commit prevents that.
Please test this PR using [this layout](https://drive.google.com/uc?id=1qFGraea6DQNBGlZEGVskkmjDwrqJMTY5). Prior to this PR, the following error will occur:
`Notice: Undefined property: lessc::$buffer in /wp-content/plugins/siteorigin-panels/widgets/lib/lessc.inc.php on line 1651`

Legacy Widgets: Change $adjustedEndCount to buffer length

---

inc/sidebars-emulator.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/962
To test this PR please enable the Sidebar Emulator setting, add a bunch of WordPress and SiteOrigin Widgets to the sidebar and if no errors are logged, it worked as expected.

Sidebar Emulator: Account for potential notice when setting widget id

---

inc/renderer.php
inc/styles.php

This PR will prevent background images set to Fixed from appearing as fixed on mobile. This is to avoid a long term (and still existing) iOS bug that results in the image being zoomed in and the length of the entire page.

Disable Fixed Background on Tablet

---

inc/renderer.php

This PR is in response to https://github.com/siteorigin/siteorigin-panels/pull/958. That PR unintentionally broke support for rows set to Full Width Stretched or Full Width Stretched Padded if there isn't another row with either a standard or full width row layout.
- Activate Corp and add [the Corp CSS Container Breaker snippet](https://github.com/siteorigin/siteorigin-panels/pull/929).
- Create a new page and add one row with an Archives widget. Give the row a background and set the **Row Layout** to **Full Width Stretched**.
- Save, and view the page. The Row won't be the full width of the page.
- Activate this PR and the row will display as expected.

CSS Container: Account for all Row Layouts When Outputting Full Width JS

---

inc/renderer.php

This PR fixes a situation where a full width row with multiple columns won't collapse correctly when the browser resolution is exactly at the Mobile Width.
- Activate Corp and add https://github.com/siteorigin/siteorigin-panels/pull/929.
- Create a new page and add a two-column row with an Archives widget in each column.
- Save, and view the page at the exact Mobile Width.
- Note that the space for the second column is still present but it disappears when you increase/decrease by 1px.
- Activate this PR and the columns will collapse as expected.

CSS Container Breaker: Prevent 1px situation Where Container Doesn Collapse Correctly

---

inc/renderer.php

This PR will prevent a situation where Page Builer can add the same full width CSS mutiple times. To test it, set up a 
- Activate Corp and add [the Corp CSS Container Breaker snippet](https://github.com/siteorigin/siteorigin-panels/pull/929).
- Add a Layout Builder to the Footer widget area and add one row with an Archives widget. Give the row a background and set the **Row Layout** to **Full Width**.
- Create a new page and add one row with an Archives widget. Give the row a background and set the **Row Layout** to **Full Width**.
- Save, and view the page. Inpsect the row and you'll see the CSS in the above screenshot.
- Activate this PR and only one instance of the above CSS will be present.

CSS Container Breaker: Only Output Full Width Global CSS once

---

inc/css-builder.php

This PR will resolve an issue where a property said to `0` can be incorrectly trip the check added in https://github.com/siteorigin/siteorigin-panels/pull/974.

add_css: Stricker `px` exclusion

---

inc/admin-layouts.php

This PR will replace the usage of `GLOB_BRACE` in favour of multiple globs. As we're only using `glob` once okay to use multiple globs like this.
To test this activate Corp and rename [this file](https://github.com/siteorigin/siteorigin-corp/blob/develop/inc/layouts/one-pager.jpg) locally to a .png (it's okay if this isn't technically valid). If the screenshot shows when looking at the bundled layouts, this PR worked as expected.

Avoid `GLOB_BRACE` For PHP 8 Compat.

---

js/siteorigin-panels/dialog/prebuilt.js

Resolve https://github.com/siteorigin/siteorigin-panels/issues/979
In a recent WordPress update, the title field was changed from an input to a div so the previous method of getting the post title no longer works. This PR accounts for the new field while also retaining the older Block Editor field and Classic Editor field

SO Layouts Block: Export Filename Fix

---

js/siteorigin-panels/dialog/widget.js

This PR will pass the post id to the server when rendering the widget form. This will allow post/page specific adjustments based on the current page. You can test this PR by opening `so-widgets-bundles/widgets/editor/editor.php` and find:
`function get_widget_form() {`
Add After:
`var_dump( $_POST['postId'] );`
This PR changes a core PB JS file so a build is required.

Pass post id to server when rendering widget form

---

compat/js/siteorigin-panels-layout-block.js
compat/js/siteorigin-panels-layout-block.jsx
compat/layout-block.php
js/siteorigin-panels/view/builder.js
js/siteorigin-panels/view/live-editor.js
tpl/js-templates.php

In a recent WP update:
- WP stopped outputting wp-data automatically.
- Removed the `core/editor` in certain contexts (mainly the new Widget Area).
This PR accounts for both of these and it adds Layout Editor and History support to the SiteOrigin Layouts Block in the new Widget area - it was a relatively simple change.
This PR modifies core JS files so a build will be required.

Restore New WP Widget Area SO Layouts Block Compatibility & Other Improvements

---

js/siteorigin-panels/model/widget.js

This PR resolves an issue with a really old version of the SiteOrigin Image widget title field being set to `false` rather than null.  For whatever reason, the Page Builder layout generation falls when boolean false is detected. This caused the Page Builder admin layout to break. The fix will ensure that no matter what, the text is a string and that'll prevent the notice.

Resolve Error Due To Invalid Widget Value Being Used as Desc

---

css/admin.less
js/siteorigin-panels/view/builder.js

This PR removes an underline (actually a shadow) added to links in the Block Editor in WordPress 6.0.
It also changes [this compatibility fix](https://github.com/siteorigin/siteorigin-panels/pull/959) to use the version body class rather than the branch class. Version is more reliable as branch won't have the minor version if it doesn't have one. This results in the class version being seen as `6` rather than `60`. This PR will require a build to test.

WP 6.0 Compatibility Changes

---

inc/admin.php

This PR prevents the following potential PHP 8.3 TypeError when previewing layouts that aren't able to render. To test this PR, simply confirm that the data is correctly detected on load by an SEO plugin or the SiteOrigin Layouts block displays correctly on load.
` Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /public_html/wp-includes/formatting.php:3238 Stack trace: #0 /public_html/wp-content/plugins/siteorigin-panels/inc/admin.php(1097): wp_targeted_link_rel('') #1 /public_html/wp-content/plugins/siteorigin-panels/inc/admin.php(209): SiteOrigin_Panels_Admin->generate_panels_preview(6514, Array) #2 /public_html/wp-admin/includes/template.php(1401): SiteOrigin_Panels_Admin->render_meta_boxes(Object(WP_Post), Array) #3 …

Prevent Potential Panels Preview PHP 8.3 TypeError

---

js/siteorigin-panels/view/builder.js

This PR resolves a sizing issue in the Layout Builder while edited via the Customizer. To test this PR, please confirm cells size correctly in the following areas:
- Customizer.
- Appearance > Widgets
- Classic or Block Editor.

Resolve Layout Builder Sizing Issue in Customizer

---

inc/admin.php

This PR prevents the changes made in https://github.com/siteorigin/siteorigin-panels/pull/995 from affecting versions of EDD before 3.0 - which is when changes were made that required our compatibility code.

EDD: Add Checks to Prevent Compatibility Changes to pre-3.0 versions.

---

js/siteorigin-panels/view/builder.js

This PR resolves the following error:
`Uncaught TypeError: l(...).attr(...).match(...) is null`
To replicate it, add a Layout Builder to a widget area via **Appearance > Widgets**. Navigate to **Appearance > Customize**, **Widgets** and open the Layout Builder. You'll get this TypeError in the console.

Prevent Layout Builder TypeError

---

inc/styles.php

@AlexGStapleton This PR makes a small update to the Attributes > Class setting description and removes several Design setting descriptions that are perhaps redundant. The extra space will hopefully make the section easier to navigate once we add the shadow and radius settings. I've moved this chat from Slack. Let me know if you're keen on these changes. No worries either way.

Settings descriptions updates

---

inc/styles.php

This is a follow up to https://github.com/siteorigin/siteorigin-panels/pull/988 which adds an opacity setting for the Box Shadow and Box Shadow Hover settings.

Box Shadow: Add Opacity Setting

---

inc/admin.php
js/siteorigin-panels/view/styles.js

This PR changes the media modal (which is accessed via the Choose Media button in the Styles) title to Choose Media. It also allows for it to be translated.
Please note that this PR changes a core JS file so a build is required.

Panels: Change media Modal Title

---

inc/renderer.php

This PR will account for a situation where the `$panels_data` is passed as a string containing JSON rather than an array.
To test this, please add a SiteOrigin Tabs widget and add a tab with Layout Builder setup present - add an archives widget. Save. Load the page in the Live Editor and make any changes to the page (you need to trigger the Live Editor to reload the preview). After the reload has occurred you'll notice the Tab contents didn't render. Switch to this branch and make another change in the Live Editor. The Tab contents will now display correctly.

Renderer: If `$panels_data` Parameter is Set, Detect String and Attempt Decode

---

js/siteorigin-panels/view/dialog.js

This PR resolves https://github.com/siteorigin/siteorigin-panels/issues/938. It's also the Page Builder's side of widget validation for the Widgets Bundle (which will interface with this and a similar event on its side). Please note that this PR modifies core PB JS files so a build is required.
Here's some test JavaScript you can try by adding them to the browser console.
This snippet is a simple way of testing validation success and failure. It causes a 50/50 chance of widget failing validation.
```
jQuery( document ).on('close_dialog_validation', function( e, values, widget, id, instance ) {
return Math.random() >= 0.5;
} );
```
This snippet applies to the Archives widget and makes the title field required. It also shows an example of indicating an issue by adding a red border around …

Panels `close_dialog_validation`: Client Side Event to Allow for Widget Validation

---

inc/styles.php

This PR adds a checkbox to make box shadows display as inset.
[MDN description of Inset](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#inset): 
> If not specified (default), the shadow is assumed to be a drop shadow (as if the box were raised above the content). The presence of the inset keyword changes the shadow to one inside the frame (as if the content was debossed inside the box). Inset shadows are drawn inside the border (even transparent ones), above the background, but below content.

Box Shadows: Add Inset Support

---

inc/admin.php
js/siteorigin-panels/view/row.js

This PR adds migration for legacy colors (legacy meaning number id to text id) and introduces the `siteorigin_panels_admin_row_colors_default` filter that allows you to change the row default colour.
[Test Layout for legacy migrations](https://drive.google.com/uc?id=1VIuywK0KqeqMbFwMsNkvrtnertCq5uEm). Before this branch, all row colors would display as the default row color. After this branch, they'll display correctly.
Test snippet:
add_filter( 'siteorigin_panels_admin_row_colors_default', function( $default ) {
return 'lime-green';
} );

Row Color: Add Migration For Legacy and Filter to Change Default

---

js/siteorigin-panels/view/row.js

This PR will resolve an issue with rows being reordered without contents being changed. To replicate, open an existing multi-row page and re-order one of the rows. Save. The re-ordering won't be retained on save. Switch to this PR and make the same reorder attempt and it will be.

Resolve Row Reordering Not Updating Correctly

---

tpl/js-templates.php

Resolve https://github.com/siteorigin/siteorigin-panels/issues/1010
This PR prevents the Row Colors container from being added if there aren't any row colors.
Before this PR:
After this PR:
A simple way to test this is to simply comment out line 105.
`// $row_colors = SiteOrigin_Panels_Admin::get_row_colors();`

Prevent Row Color Spacing If No Row Colors

---

css/admin.less

This PR will allow row colors to wrap and centers them.
It also sets the default active color for rows and hover color for cell dividers.
This PR will require a build.

Row Color Adjustments
