- inc/widgets.php
Adding  Jetpack, BBpress sections Woocommerce sections in widgets selector.
> Adding Jetpack, BBpress sections Woocommerce

- siteorigin-panels.php
> Allow theme to adjust the layout opening tag

- inc/styles.php
- js/siteorigin-panels-styles.js
- js/siteorigin-panels.js
Allow siteorigin_panels_row_style_fields and siteorigin_panels_widget_style_fields to know from which post_id they are called.
> Current post id to style fields filters

- siteorigin-panels.php
Now it is easy to add CSS styling on widget id.
> Add panel delta number to $panels_data

- siteorigin-panels.php
Provide mechanism to set classes on the widget wrapper.
> Allow themes and plugins to alter the widget wrapper classes

- inc/styles.php
- js/siteorigin-panels-styles.js
Add support for 'multiple' attribute in measurement field definition
> Allow multi values in measurement field

- siteorigin-panels.php
Hi Guys,
I hope it's not a trouble for you :-)
Thanks,
Vlad.
> Added filters to cell margin bottom

- siteorigin-panels.php
> Add classname of the widget to HTML output if classname is defined

- inc/sidebars-emulator.php
> Improve check for the homepage in sidebars simulator. Related to #73.

- siteorigin-panels.php
> Widget links color

- inc/default-styles.php
> Setting field for link colors

- siteorigin-panels.php
when rendering widget forms to resolve GH-124.
> Added `in_widget_form` action 

- css/admin.css
- css/admin.less
- js/siteorigin-panels.js
- js/siteorigin-panels/dialog/prebuilt.js
- js/siteorigin-panels/view/dialog.js
- tpl/js-templates.php
Basic dialog button handling for elements in toolbar with .so-toolbar-button class.
> Dropdown button for prebuilt dialog options.

- settings/settings.php
- siteorigin-panels.php
#177 I've added a checkbox in settings so a user can activate "margin in last row" for every site.
If the user only want a margin in last row he can overwrite it with the row styles like @jordif did.
(Need that feature on some of my sites. At the moment i'm adding a empty row on the bottom to each page for this feature)
> Added last row margin features

- js/siteorigin-panels.js
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/view/styles.js
This happens when style fields have been filtered out.
To resolve GH-132.
> Hide empty right sidebar in row/widget dialogs.

- css/admin.css
- css/admin.less
- inc/live-editor.php
- js/siteorigin-panels.js
- js/siteorigin-panels/collection/cells.js
- js/siteorigin-panels/collection/widgets.js
- js/siteorigin-panels/dialog/history.js
- js/siteorigin-panels/dialog/prebuilt.js
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/dialog/widgets.js
- js/siteorigin-panels/main.js
- js/siteorigin-panels/model/builder.js
- js/siteorigin-panels/utils/menu.js
- js/siteorigin-panels/view/builder.js
- js/siteorigin-panels/view/cell.js
- js/siteorigin-panels/view/dialog.js
- js/siteorigin-panels/view/live-editor.js
- js/siteorigin-panels/view/row.js
- js/siteorigin-panels/view/styles.js
- js/siteorigin-panels/view/widget.js
- siteorigin-panels.php
- tpl/admin-home-page.php
- tpl/js-templates.php
- tpl/metabox-panels.php
- widgets/basic.php
Several improvements to the live editor. Most importantly, we now have a complete builder interface in the right column and there are a few improvements to how we reload the preview to make it feel more responsive.
> New Live Editor

- widgets/basic.php
To resolve Widgets Bundle [issue 146](https://github.com/siteorigin/so-widgets-bundle/issues/146).
@gregpriday Very small change, but would just like your input on potential impact.
> Fix issue where Layout Builder widget wasn't saving all fields.

- js/siteorigin-parallax.js
> Ensure Parallax is run when DOM ready

- js/styling.js
#296 
We don't use it so it's pointless to keep this here.
> Remove Stellar setup in styling.js

- inc/default-styles.php
Resolves #257. Copy of #310 for SiteOrigin Page Builder 2.x
> Add Fixed background support

- widgets/basic.php
Seems odd to allow people to filter this on a global level.
Adds siteorigin_panels_postloop_query_args filter
> Post Loop: Add filter for query

- css/admin.css
- css/admin.less
- inc/default-styles.php
- inc/renderer.php
- inc/styles.php
- js/siteorigin-panels.js
- js/siteorigin-panels/collection/cells.js
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/model/builder.js
- js/siteorigin-panels/model/cell.js
- js/siteorigin-panels/model/row.js
- js/siteorigin-panels/view/builder.js
- js/siteorigin-panels/view/cell.js
- js/siteorigin-panels/view/row.js
- js/siteorigin-panels/view/styles.js
- tpl/js-templates.php
Still needs some spit 'n polish, but creating the PR so long for easier initial review and feedback.
> Cell styles WIP

- inc/admin.php
- inc/default-styles.php
- inc/renderer.php
- inc/styles-admin.php
- inc/styles.php
- siteorigin-panels.php
This is a fairly large refactoring of how row/cell/widget styling works. I've renamed a few things and added a few filters to make it easier for developers to add their own styling CSS.
> Move style CSS into general CSS object

- css/admin.less
- inc/admin.php
- inc/post-content-filters.php
- inc/renderer.php
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/model/builder.js
- js/siteorigin-panels/model/widget.js
- js/siteorigin-panels/view/dialog.js
- js/siteorigin-panels/view/row.js
- js/siteorigin-panels/view/widget.js
- tpl/js-templates.php
> Row labels

- inc/styles.php
> Ensure custom CSS is properly formed

- inc/admin.php
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/view/widgets/js-widget.js
- js/siteorigin-panels/view/widgets/media-widget.js
- js/siteorigin-panels/view/widgets/text-widget.js
This resolves #420. Compatibility with new WP 4.8 widgets.
> WP 4.8 Compatibility

- css/admin.less
- inc/admin-tutorials.php
- inc/admin.php
- js/siteorigin-panels/view/builder.js
- tpl/js-templates.php
Adds a simple way for users to view our educational content inside Page Builder.
> Tutorials dropdown

- inc/admin.php
- inc/settings.php
- settings/tpl/help.php
- tpl/help.php
- tpl/js-templates.php
- widgets/widgets.php
- widgets/widgets/button/tpl/simple.php
Related siteorigin/so-widgets-bundle#588
Reference: https://mathiasbynens.github.io/rel-noopener
[Slack Reference](https://siteorigin.slack.com/archives/C02SXRL8N/p1509362961000191)
> Add noopener for all instances of _blank

- inc/renderer.php
To resolve #466 This adds a filter to allow third party developers to modify or remove inline styles.
> Inline styles filter

- css/admin.less
- inc/admin-layouts.php
- js/siteorigin-panels/dialog/prebuilt.js
- js/siteorigin-panels/view/dialog.js
- tpl/js-templates.php
We need to decide if this is the best way for themes to include JSON layouts. Basically, the function gives themes a way of adding a prebuilt layout from a JSON file using the standard prebuilt layouts filter.
> Added way of loading prebuilt layouts through JSON

- inc/admin.php
- inc/settings.php
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widgets.js
- js/siteorigin-panels/view/cell.js
- js/siteorigin-panels/view/widget.js
Resolves https://github.com/siteorigin/siteorigin-panels/issues/142
> Implement instant open feature

- css/admin.less
> row and cell styles display issue (backend)

- js/yoast-compat.js
To fix #572. Custom widget content handler for WB Accordion and Tabs widgets.
> Fix for WB Tabs and Accordion widgets' content in Yoast

- inc/widgets/post-loop-helper.php
- inc/widgets/post-loop.php
Follow up to #559.
This PR will allow for the custom post loop to load in all situations and allow for its file name to appear in the template drop down.
> Post Loop: Fix post title and inclusion issue

- css/admin.less
- inc/styles-admin.php
> Add Radio Styles field

- inc/renderer.php
- inc/styles-admin.php
- inc/styles.php
> Mobile styles

- compat/js/siteorigin-panels-layout-block.js
- compat/js/siteorigin-panels-layout-block.jsx
- compat/layout-block.php
- inc/admin.php
- inc/widgets/layout.php
- js/siteorigin-panels/dialog/widgets.js
- js/siteorigin-panels/view/cell.js
- readme.txt
- siteorigin-panels.php
* Added setting for mobile specific margin.
* Prevent Welcome Page Redirect During Bulk Install and TGMPA
* Added support for password settings field.
* Layout Block: Add filter to control whether Add Layout Block button is shown or not.
* Fixed issue with widget duplication after moving a widget.
* Fixed Read More Custom Text issue.
> Release 2.10.7

- inc/styles.php
Basics of the setting are in place and working. We just need to decide on language to use. Should this be called mobile cell spacing/margin/gutter?
> Added setting for cell spacing in a collapsed row

- inc/renderer.php
> Restore Cell Bottom Margin on tablets

- inc/renderer.php
Resolve #667 #733
Please refer to #733 for a child theme that will allow you to replicate this issue - it's possible to replicate this issue without it, it's just simplier.
> Prevent Live Editor Notice that can appear when using SO Renderer outside of main loop

- siteorigin-panels.php
Resolves https://github.com/siteorigin/siteorigin-panels/issues/742
> Exclude Black Studio TinyMCE Widget Title from Excerpt

- inc/live-editor.php
- siteorigin-panels.php
Resolves #748
@Misplon Please confirm the test.html file I sent you the other day over Slack still works as expected for you.
> Fix preview issue when using Live Editor before saving

- compat/js/siteorigin-panels-layout-block.js
- compat/js/siteorigin-panels-layout-block.jsx
- inc/admin.php
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/jquery/setup-builder-widget.js
- js/siteorigin-panels/main.js
- js/siteorigin-panels/view/builder.js
- js/siteorigin-panels/view/cell.js
- js/siteorigin-panels/view/styles.js
- js/yoast-compat.js
This PR fixes our live Yoast integration in the classic editor. It also resolves https://github.com/siteorigin/siteorigin-panels/issues/675 and https://github.com/siteorigin/siteorigin-panels/issues/647
> Improved Yoast Comatability

- js/siteorigin-panels/view/live-editor.js
> Live Editor: Retain Device Mode Sizing on panelUpdate

- css/admin.less
Resolve https://github.com/siteorigin/siteorigin-panels/issues/718.
The description is hidden to achieve this.
> Admin: Show Widget Action links on mobile devices

- inc/widgets/post-loop.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/791
> Post Loop: Resolve notice when used outside of Page Builer

- inc/admin.php
- inc/styles.php
- siteorigin-panels.php
Requires https://github.com/siteorigin/plugin-build/pull/16
> Remove version from core JS files urls

- js/siteorigin-panels/dialog/prebuilt.js
Resolve https://github.com/siteorigin/siteorigin-panels/issues/798
The title wasn't previously showing as the Block Editor title field is set up slightly differently.
> Layout Export: Fix post title detection in Block Editor

- inc/renderer.php
- inc/settings.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/799
> Add Global Setting "Row Mobile Bottom Margin"

- compat/js/siteorigin-panels-layout-block.js
- compat/js/siteorigin-panels-layout-block.jsx
This PR prevents previewing issues that can occur when `Layout Block Default Mode` is set to `Edit`. This PR also ensures the preview isn't reInitialized unnecessarily.
> Layout Block: Trigger WB widget display when showing preview

- inc/widgets/post-loop.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/704
> SiteOrigin Layout: Allow Post Loop widget to be previewed

- inc/renderer.php
- inc/settings.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/816
> Add Output Page Builder Layout CSS setting

- compat/js/siteorigin-panels-layout-block.js
- compat/js/siteorigin-panels-layout-block.jsx
- js/siteorigin-panels/dialog/history.js
- js/siteorigin-panels/dialog/prebuilt.js
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widgets.js
- js/siteorigin-panels/jquery/setup-builder-widget.js
- js/siteorigin-panels/main.js
- js/siteorigin-panels/model/builder.js
- js/siteorigin-panels/model/widget.js
- js/siteorigin-panels/utils/menu.js
- js/siteorigin-panels/view/builder.js
- js/siteorigin-panels/view/cell.js
- js/siteorigin-panels/view/dialog.js
- js/siteorigin-panels/view/live-editor.js
- js/siteorigin-panels/view/row.js
- js/siteorigin-panels/view/styles.js
- js/siteorigin-panels/view/widget.js
- js/styling.js
- settings/admin-settings.js
- tpl/js-templates.php
WB PR: https://github.com/siteorigin/so-widgets-bundle/pull/1208
A large number of changes were made - too many to really list in a readable way. Test _everything_.
> jQuery Migrate / WP 5.6 changes

- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/view/row.js
This PR resolves an issue that prevents rows from being sized correctly when resized via the Add/Edit Row model.
It also updates some deprecated code related to rows.
> Resolve Row Cell sizing Issue

- inc/settings.php
This will only affect new installs.
> Change Instant Open Widget default setting

- inc/admin.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/903
> Plugin Links: Add Settings Link

- compat/acf-widgets.php
- js/siteorigin-panels/view/dialog.js
Resolve https://github.com/siteorigin/siteorigin-panels/issues/900
To test this please add a repeater field. Add a standard field (ie. Text) and a repeater field inside to the repeater. Enable it for all widgets and then save. Try and use these fields.
> ACF Improved Repeater Support

- inc/renderer.php
- inc/styles-admin.php
- inc/styles.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/738
Duplicate of mobile settings bar the Mobile Cell Margins. While testing this PR, please disable the Tablet Layout during testing to confirm settings disappear and settings no longer take effect.
> Tablet Styles

- inc/styles.php
This will correct tablet and widget styles and remove their dependency on the Row Tablet Layout.
> Tablet Styles Widgets: Correct Filter and Style

- compat/js/siteorigin-panels-layout-block.js
This PR adds the complied version of https://github.com/siteorigin/siteorigin-panels/pull/927
> Update Complied SO Layouts Block JS

- css/admin.less
- js/siteorigin-panels/dialog/row.js
- js/siteorigin-panels/dialog/widget.js
- js/siteorigin-panels/view/row.js
- js/siteorigin-panels/view/widget.js
This PR will fade a row/widget if the row is set to hidden on any device or any user logged-in status.
> Toggle Visibility: Row/Widget Fades

- compat/yoast.php
- siteorigin-panels.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/965
Video data is indexed when saving the page and after 30 days. The user must manually save the page to ensure data is updated.
> Add compat yoast seo video

- inc/admin.php
This PR will restore Yoast SEO Content Analysis compatibility in newer versions of Yoast.
> Yoast Compat: Check for New Yoast Script

- inc/css-builder.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/973
> Don't add properties with only a `px` set

- inc/renderer.php
This filter will allow for a widget/row output to be prevented via a filter.
> Add `siteorigin_panels_output_row/widget` filters

- inc/admin.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/994
>  Correct Add New button Issue for EDD Downloads Page

- inc/renderer.php
- siteorigin-panels.php
- widgets/widgets.php
When displaying inline style or script tags, check if the theme supports html5.
> HTML Validation Improvements.

- inc/styles.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/1001
> Styles: Add Border Radius Setting

- inc/styles-admin.php
Resolve https://github.com/siteorigin/siteorigin-panels/issues/1015
> Styles: Add Viewport Units of Measurement
